id: PF242844E
initial_creation_type: ocr
source_metadata:
  volumes:
    50b3c28c1d0142afaaf9f4e2b05d4cb5:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རིགས་ལྡན་མའི་དེ་ཁོ་ན་ཉིད་ངེས་པ།
      total_pages: 1544
      volume_number: 12
